-- 1.	What are the details of all cars purchased in the year 2022? --
select 
	s.sale_id, 
    s.car_id, 
    s.salesman_id, 
    s.purchase_date,
	c.car_id,
    c.make,
    c.style,
    c.type,
    c.cost_$,
    sp.salesman_id,
    sp.name,
    sp.age,
    sp.city
from sales s 
join salespersons sp on s.salesman_id = sp.salesman_id
join cars c on s.car_id = c.car_id
where YEAR(s.purchase_date) > 2021;

-- 2.	What is the total number of cars sold by each salesperson? -- 
select 
	sp.salesman_id,
    sp.name,
    count(s.sale_id) 
as Num_of_cars_sold 
from sales s 
join salespersons sp 
on s.salesman_id = sp.salesman_id 
group by sp.salesman_id;

-- 3.	What is the total revenue generated by each salesperson? -- 
select 
	sp.salesman_id,
    sp.name,
   -- (this is optional) count(s.sale_id) as Num_of_cars_sold , 
    sum(c.cost_$) as Total_Sales
from sales s 
join salespersons sp 
on s.salesman_id = sp.salesman_id 
join cars c 
on s.car_id = c.car_id
group by sp.salesman_id;

-- 4.	What are the details of the cars sold by each salesperson? --
select 
    sp.salesman_id,
    sp.name as Sales_Person,
    c.*
    from sales s 
join salespersons sp 
on s.salesman_id = sp.salesman_id 
join cars c 
on s.car_id = c.car_id;

-- 5.	What is the total revenue generated by each car type? --
select 
	c.type as Car_Type,
    c.car_id as Car_Id,
    sum(c.cost_$) as Rev_Generated
    from sales s 
join cars c 
on s.car_id = c.car_id
group by c.car_id
;

-- 6.	What is the total revenue generated by the sales of hatchback cars? --
select 
	c.style as Car_Style,
	c.type as Car_Type,
    c.car_id as Car_Id,
    sum(c.cost_$) as Rev_Generated
    from sales s 
join cars c 
on s.car_id = c.car_id
where c.style = 'hatchback'
group by c.car_id
;

-- 7.	What are the details of the cars sold in the year 2021 by salesperson ‘Emily Wong’? --
select 
	s.sale_id, 
    c.make, 
    c.type, 
    c.style, 
    c.cost_$, 
    s.purchase_date
from sales s
join cars c on s.car_id = c.car_id
join salespersons sp on s.salesman_id = sp.salesman_id
where sp.name = 'Emily Wong' 
and 
year(s.purchase_date) = 2021;

-- 8.	What is the total revenue generated by the sales of SUV cars in the year 2022? -- 
select 
    c.car_id as Car_Id,
	c.style as Car_Style,
	c.type as Car_Type,
    sum(c.cost_$) as Rev_Generated
    from sales s 
join cars c 
on s.car_id = c.car_id
where c.style = 'SUV'
and 
year(s.purchase_date) = 2022
group by c.car_id
;

-- 9.	What is the name and city of the salesperson who sold the most number of cars in the year 2023? --
select 
    sp.salesman_id as Salesman_ID,
    sp.name as Salesman_Name,
    sp.city as City,
    count(s.car_id) as Cars_Sold
    from salespersons sp 
join sales s 
on sp.salesman_id = s.salesman_id 
where year(s.purchase_date) = 2023
group by 
	sp.salesman_id,
    sp.name,
    sp.city
order by Cars_Sold desc
    limit 1;

-- 10.	What is the name and age of the salesperson who generated the highest revenue in the year 2022? -- 
select 
	sp.name, 
    sp.age, 
    sum(c.cost_$) AS total_revenue
from salespersons sp
join sales s on sp.salesman_id = s.salesman_id
join cars c on s.car_id = c.car_id
where year(s.purchase_date) = 2022
group by 
	sp.name, 
    sp.age
order by total_revenue desc
    limit 1;
    
    
SELECT 
	sp.name, 
    sp.age, 
    sum(c.cost_$) AS total_revenue
FROM salespersons sp
join sales s on sp.salesman_id = s.salesman_id
join cars c on s.car_id = c.car_id
WHERE YEAR(s.purchase_date) = 2022
GROUP BY 
	sp.name, 
    sp.age
HAVING SUM(c.cost_$) <= (
    SELECT MAX(total_revenue)
    FROM (
        SELECT 	sp.name, 
				sp.age, 
				sum(c.cost_$) AS total_revenue
        FROM salespersons sp
        join sales s on sp.salesman_id = s.salesman_id
        WHERE YEAR(s.purchase_date) = 2022
        GROUP BY 	sp.name, 
					sp.age
    ) AS RevenueTable
)
